baseurl = "https://fenglb.cn"
title = "Bobby Love"
author = "Lingbing Feng"
canonifyurls = true
languagecode = "en"
theme = "hugo-lithium"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Lingbing Feng's Blog"

[[menu.main]]
    name = "Home"
    url = "https://fenglb.cn"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/lingbing"
    weight = 2
