baseurl = "https://fenglb.cn"
title = "Bobby Love"
author = "Lingbing Feng"
canonifyurls = true
languagecode = "en"

relativeURLS = true
enableRobotsTXT = true
canonifyURLs = true
preserveTaxonomyNames = true
paginate = 7
pluralizeListTitles = false
theme = "hugo-future-imperfect"


googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Lingbing Feng's Blog"

[[menu.main]]
    name = "Home"
    url = "https://fenglb.cn"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/lingbing"
    weight = 2


[params.intro]
  header    = "Lingbing Feng"
  paragraph = ""
  about     = ""
  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
  [params.intro.pic]
    src       = "static/img/main/lingbing.jpg"
    # Sets Image to be a cirlce
    circle    = false
    # Sets Image to be Future Imperfect's hexagon
    imperfect = true
    width     = ""
    alt       = "head"